name: Security Check

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and upgrade vulnerable packages
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install --upgrade requests
          pip install -r requirements.txt
          pip install pip-audit bandit safety

      - name: Run pip-audit
        run: |
          source venv/bin/activate
          pip-audit

      - name: Run bandit
        run: |
          source venv/bin/activate
          bandit -r .

      - name: Run safety
        run: |
          source venv/bin/activate
          safety check
